name: curve-stableswap-ng
contracts_folder: contracts/main/

plugins:
  - name: vyper
  - name: alchemy
  - name: hardhat
  - name: ledger
  - name: etherscan
  - name: arbitrum
  - name: optimism
  - name: polygon
  - name: gnosis

default_ecosystem: ethereum

# vyper:
#   default_version: paris # enable for non PUSH0 evm networks
#   ethereum:
#     evm_version: shanghai

hardhat:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
      sepolia:
        upstream_provider: alchemy
    arbitrum:
      mainnet:
        upstream_provider: geth

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    transaction_acceptance_timeout: 99999999
    default_provider: hardhat
  mainnet:
    transaction_acceptance_timeout: 99999999
  sepolia:
    transaction_acceptance_timeout: 99999999

arbitrum:
  default_network: mainnet-fork
  mainnet_fork:
    transaction_acceptance_timeout: 99999999
    default_provider: hardhat
  mainnet:
    transaction_acceptance_timeout: 99999999

geth:
  ethereum:
    mainnet:
      uri: http://localhost:9090
  arbitrum:
    mainnet:
      uri: https://arb-mainnet.g.alchemy.com/v2/{some_key}

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
