on: [pull_request, push]

name: lint

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - uses: pre-commit/action@v3.0.0
