name: test_gauge

on: [pull_request, push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WEB3_PROVIDER_URL: ${{ secrets.WEB3_PROVIDER_URL }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.vvm
          key: compiler-cache

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Install Requirements
        run: |
          pip install poetry==1.5.1
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run All Token Tests 18,18
        run: |
          source .venv/bin/activate
          pytest tests/pools/ --pool-size=2 --pool-type=basic --decimals=18,18 -n auto

      - name: Run Plain Tests 18,6
        run: |
          source .venv/bin/activate
          pytest tests/pools/ --pool-size=2 --pool-type=basic --token-types=plain --decimals=18,6 -n auto
