# TODO: split actions later
name: tests

on: ["push", "pull_request"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.vvm
          key: compiler-cache

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Install Requirements
        run: |
          pip install poetry==1.5.1
          poetry install

      - name: Run Tests
        run: pytest tests -n auto
