name: test_token

on: [pull_request, push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache Compiler Installations
        uses: actions/cache@v3
        with:
          path: |
            ~/.vvm
          key: compiler-cache

      - name: Setup Python 3.10.4
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.4

      - name: Install Requirements
        run: |
          pip install poetry==1.5.1
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --without dev

      - name: Run Tests
        run: |
          source .venv/bin/activate
          pytest tests/test_token.py --token-types=plain -n auto
